Repository nervosnetwork/mercury, pull requests merged in 2021-11, with the labels that each got.

#277 chore: remove useless monitor code
  common/src/lib.rs
  core/storage/src/relational/mod.rs
Labels: pr_chore

#278 chore: release v0.2.0-beta.3 version
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  core/cli/Cargo.toml
  core/extensions/Cargo.toml
  core/inspection/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/storage/Cargo.toml
  core/synchronization/Cargo.toml
  docker-compose.yml
Labels: pr_chore

#283 fix: always goto synchronization when restart
  Cargo.lock
  core/service/src/lib.rs
Labels: pr_fix

#289 feat(sync): develop the synchronization of indexer cell table
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/tests/operation_test.rs
  core/service/src/lib.rs
  core/storage/Cargo.toml
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/insert.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/sql.rs
  core/storage/src/relational/table.rs
  core/storage/src/relational/tests/get_cell_test.rs
  core/storage/src/relational/tests/mod.rs
  core/storage/src/relational/tests/other_test.rs
  core/synchronization/Cargo.toml
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
  core/synchronization/src/table.rs
  db/xsql-test/Cargo.toml
  db/xsql-test/src/lib.rs
  db/xsql-test/src/sql.rs
  db/xsql/Cargo.toml
  db/xsql/src/lib.rs
  db/xsql/src/page.rs
  devtools/create_table/create_table.sql
Labels: pr_feat

#285 docs(sync): add synchronization design document
  core/synchronization/README.md
  docs/assets/sync_flow.jpg
Labels: pr_docs

#303 fix(storage): get tx_hash when query transaction by script
  Cargo.lock
  Cargo.toml
  apm/tracing/Cargo.toml
  core/cli/Cargo.toml
  core/inspection/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/storage/Cargo.toml
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/sql.rs
  core/synchronization/Cargo.toml
  db/xsql/Cargo.toml
  db/xsql/src/page.rs
  devtools/create_table/create_table.sql
Labels: pr_chore, pr_fix

#306 refactor(storage): change query distinct indexer cell
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  core/storage/Cargo.toml
  core/storage/src/relational/_sql.html
  core/storage/src/relational/mod.rs
  core/storage/src/relational/sql.rs
  core/storage/src/relational/table.rs
Labels: pr_refactor

#302 docs(config): add the document of config instruction
  README.md
  common/src/lib.rs
  common/src/utils.rs
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/rpc/src/lib.rs
  core/storage/src/relational/mod.rs
  db/xsql/src/page.rs
  devtools/config/docker_compose_config.toml
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
  docs/config.md
Labels: pr_docs

#308 chore: release v0.2.0-beta.4 version
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  core/cli/Cargo.toml
  core/extensions/Cargo.toml
  core/inspection/Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/storage/Cargo.toml
  core/synchronization/Cargo.toml
  docker-compose.yml
Labels: pr_chore

#313 docs: update README
  README.md
Labels: pr_docs

#314 docs: add detailed setup instructions
  README.md
  docs/setup.md
Labels: pr_docs

#316 fix(storage): get db tip from block table
  Cargo.lock
  core/storage/src/relational/sql.rs
Labels: pr_fix

#317 refactor(sql): change sql return type and index type
  Cargo.lock
  core/storage/src/relational/mod.rs
  core/storage/src/relational/sql.rs
  core/storage/src/relational/table.rs
  devtools/create_table/create_table.sql
Labels: pr_refactor

#319 refactor(DB): rollback tx when failed rather than close connection
  core/storage/src/relational/mod.rs
  core/synchronization/src/lib.rs
  db/xsql/src/lib.rs
  src/main.rs
Labels: pr_refactor

#323 feat(config): export some DB connection config
  Cargo.lock
  clippy.toml
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/rpc/core/src/tests/mod.rs
  core/service/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/tests/mod.rs
  core/synchronization/src/sql.rs
  db/xsql/src/lib.rs
  devtools/config/docker_compose_config.toml
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
  docs/config.md
Labels: pr_feat

#324 fix(rpc): return error instead unreachable!()
  common/src/address.rs
  core/rpc/core/src/error.rs
  core/rpc/core/src/impl/utils.rs
  core/rpc/types/src/error.rs
  core/rpc/types/src/lib.rs
Labels: pr_fix

#325 refactor(common): use full address global
  Cargo.lock
  common/src/address.rs
  common/src/utils.rs
  core/rpc/core/src/impl/adjust_account.rs
  core/rpc/core/src/impl/utils.rs
Labels: pr_refactor
