Repository nervosnetwork/mercury, pull requests merged in 2021-08, with the labels that each got.

#95 feat(DB): impl append block interface for xsql
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  core/cli/src/lib.rs
  db/postgres/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/Cargo.toml
  db/xsql/src/error.rs
  db/xsql/src/insert.rs
  db/xsql/src/lib.rs
  db/xsql/src/plugin.rs
  db/xsql/src/sql.rs
  db/xsql/src/table.rs
  devtools/create_table/create_table.sql
  devtools/create_table/main.py
Labels: pr_feat

#96 chore: cargo update and format rbatis proc macro
  Cargo.lock
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
  db/xsql/src/table.rs
Labels: pr_chore

#97 refactor(DB): change cursor type to i64
  common/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/lib.rs
Labels: pr_refactor

#98 refactor(DB): change some column from varchar to bytea
  db/xsql/src/insert.rs
  db/xsql/src/lib.rs
  db/xsql/src/table.rs
  devtools/create_table/create_table.sql
Labels: pr_refactor

#99 feat: add sync process and change some column type
  Cargo.lock
  db/protocol/src/lib.rs
  db/xsql/Cargo.toml
  db/xsql/src/fetch.rs
  db/xsql/src/insert.rs
  db/xsql/src/lib.rs
  db/xsql/src/sql.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/table.rs
  devtools/create_table/create_table.sql
Labels: pr_feat

#100 feat(DB): add mercury snowflake generator
  Cargo.lock
  Cargo.toml
  core/service/Cargo.toml
  db/protocol/src/lib.rs
  db/xsql/Cargo.toml
  db/xsql/benches/snowflake_bench.rs
  db/xsql/src/insert.rs
  db/xsql/src/lib.rs
  db/xsql/src/plugin.rs
  db/xsql/src/snowflake.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/table.rs
  devtools/create_table/create.py
  devtools/create_table/create_table.sql
Labels: pr_feat

#101 feat(DB): sync canonical chain and change snowflake generator
  Cargo.lock
  db/xsql/src/snowflake.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/table.rs
Labels: pr_feat

#104 refactor(DB): change rbatis url that use bson instead of json
  Cargo.lock
  common/src/lib.rs
  db/xsql/Cargo.toml
  db/xsql/src/fetch.rs
  db/xsql/src/insert.rs
  db/xsql/src/lib.rs
  db/xsql/src/sql.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/table.rs
Labels: pr_refactor

#105 refactor(DB): change value uncles_hash to uncle_hashes
  Cargo.lock
  db/xsql/src/fetch.rs
  db/xsql/src/insert.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/table.rs
Labels: skip_changelog

#106 feat(DB): add rollback block process
  Cargo.lock
  db/xsql/src/error.rs
  db/xsql/src/insert.rs
  db/xsql/src/lib.rs
  db/xsql/src/remove.rs
  db/xsql/src/sql.rs
Labels: pr_feat

#108 feat(DB): add cursor page plugin and query scripts
  Cargo.lock
  common/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
  db/xsql/src/page.rs
  db/xsql/src/remove.rs
  db/xsql/src/table.rs
Labels: pr_feat

#109 feat(DB): add query live cells interface
  Cargo.lock
  common/src/lib.rs
  db/xsql/src/error.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
Labels: pr_feat

#110 fix(DB): get order from page request instead of args
  Cargo.lock
  db/xsql/src/fetch.rs
  db/xsql/src/page.rs
Labels: pr_fix

#114 refactor: change storage from rocksdb to xsql
  Cargo.lock
  clippy.toml
  common/src/lib.rs
  core/cli/Cargo.toml
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/extensions/src/ckb_balance/mod.rs
  core/extensions/src/ckb_balance/types.rs
  core/extensions/src/lib.rs
  core/extensions/src/lock_time/mod.rs
  core/extensions/src/lock_time/types.rs
  core/extensions/src/rce_validator/mod.rs
  core/extensions/src/rce_validator/types.rs
  core/extensions/src/script_hash/mod.rs
  core/extensions/src/script_hash/types.rs
  core/extensions/src/special_cells/mod.rs
  core/extensions/src/special_cells/types.rs
  core/extensions/src/tests/creation.rs
  core/extensions/src/tests/extension_test.rs
  core/extensions/src/tests/memory_store.rs
  core/extensions/src/tests/mod.rs
  core/extensions/src/types.rs
  core/extensions/src/udt_balance/mod.rs
  core/extensions/src/udt_balance/types.rs
  core/rpc/Cargo.toml
  core/rpc/src/ckb_client.rs
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/memory_db.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/operation_test.rs
  core/rpc/src/tests/query_test.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/rpc/src/types.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/service/src/middleware.rs
  core/storage/Cargo.toml
  core/storage/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
  db/xsql/src/page.rs
  db/xsql/src/table.rs
  db/xsql/src/tests/mod.rs
  devtools/config/testnet_config.toml
Labels: pr_refactor

#116 feat(service): sync blocks in parallel when start mercury
  Cargo.lock
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/rpc/src/ckb_client.rs
  core/rpc/src/lib.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/storage/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
  db/xsql/src/sql.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/table.rs
  devtools/config/testnet_config.toml
  devtools/create_table/create_sqlite_table.sql
  devtools/create_table/create_table.sql
Labels: pr_feat

#117 feat(rpc): add some basic functions and tools
  common/src/lib.rs
  core/rpc/src/ckb_client.rs
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/types.rs
  core/storage/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
Labels: pr_feat

#119 feat(DB): add some new interfaces and abort when panic
  Cargo.lock
  Cargo.toml
  core/rpc/src/rpc_impl/utils.rs
  core/storage/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
  db/xsql/src/tests/mod.rs
  src/main.rs
Labels: pr_feat

#120 refactor(DB): get block from node in spawn task instead of main thread
  Cargo.lock
  Cargo.toml
  common/src/utils.rs
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/types.rs
  core/service/src/lib.rs
  core/storage/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/fetch.rs
  db/xsql/src/lib.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/tests/mod.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
  src/main.rs
Labels: pr_refactor

#121 feat(rpc): add pool token and change asset type to strcut
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/types.rs
  core/service/src/lib.rs
  core/storage/src/lib.rs
  db/protocol/src/lib.rs
  db/xsql/src/lib.rs
  db/xsql/src/snowflake.rs
  db/xsql/src/sql.rs
Labels: pr_feat

#129 feat(config): add need synchronization config
  Cargo.lock
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/rpc/src/tests/mod.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/storage/Cargo.toml
  core/storage/src/lib.rs
  db/xsql/src/lib.rs
  db/xsql/src/synchronize.rs
  db/xsql/src/tests/mod.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_feat

#130 refactor: change empty type script hash to H256 default
  core/cli/src/config.rs
  core/cli/src/lib.rs
  db/xsql/src/table.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_refactor

#131 refactor(DB): save batch tx cell and script in one block
  db/xsql-test/src/sql.rs
  db/xsql/src/insert.rs
  db/xsql/src/table.rs
Labels: pr_refactor

#141 feat(rpc): add get account number interface
  Cargo.lock
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/service/Cargo.toml
Labels: pr_feat
