Repository nervosnetwork/mercury, pull requests merged in 2021-07, with the labels that each got.

#48 feat(rpc): transfer completion support using claimable source
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/address.rs
  common/src/lib.rs
  core/cli/Cargo.toml
  core/cli/src/lib.rs
  core/extensions/Cargo.toml
  core/extensions/src/ckb_balance/mod.rs
  core/extensions/src/lib.rs
  core/extensions/src/lock_time/mod.rs
  core/extensions/src/special_cells/mod.rs
  core/rpc/Cargo.toml
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/query_test.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/rpc/src/types.rs
  core/service/src/lib.rs
Labels: pr_feat

#53 refactor(rpc): change handle cheque process
  Cargo.lock
  common/Cargo.toml
  common/src/hash.rs
  common/src/lib.rs
  core/extensions/src/special_cells/mod.rs
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/rpc/src/types.rs
Labels: pr_refactor

#55 chore(config): change cheque config in mainet into real
  Cargo.lock
  devtools/config/mainnet_config.toml
Labels: pr_chore

#54 feat(rpc): change an exact fee into fee rate when build transaction
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/rpc/src/types.rs
Labels: pr_feat

#56 refactor(rpc): get balance interface argument and response
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/tests/query_test.rs
  core/rpc/src/types.rs
Labels: pr_refactor

#57 refactor: remove the assertation of acp script args len
  Cargo.lock
  core/extensions/src/special_cells/mod.rs
Labels: pr_refactor

#58 fix: calculate tx size missing offset
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/transfer_completion_test.rs
Labels: pr_fix

#59 refactor(rpc): change the get balance interface
  Cargo.lock
  common/src/address.rs
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/query_test.rs
  core/rpc/src/types.rs
  core/service/src/lib.rs
Labels: pr_refactor

#61 feat: add script hash extension and register address rpc interface
  core/extensions/src/lib.rs
  core/extensions/src/script_hash/mod.rs
  core/extensions/src/script_hash/types.rs
  core/extensions/src/tests/mod.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/operation.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_feat

#62 feat(rpc): add get generic transaction and generic block interface
  Cargo.lock
  core/rpc/src/ckb_client.rs
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/types.rs
Labels: pr_feat

#63 feat(extension): add index tx block number and hash extension
  core/extensions/src/script_hash/mod.rs
  core/extensions/src/script_hash/types.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/operation_test.rs
Labels: pr_feat

#64 refactor(rpc): buid transfer transaction and wallet creation
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/operation_test.rs
  core/rpc/src/tests/query_test.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/rpc/src/types.rs
Labels: pr_refactor

#65 fix(rpc): cannot get cell by out point when it has been consumed
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/service/src/lib.rs
Labels: pr_fix

#68 refactor: return error when the ckb rpc return none
  core/rpc/src/ckb_client.rs
  core/rpc/src/rpc_impl.rs
Labels: pr_refactor

#69 refactor: storage code hash of acp address payload
  common/src/address.rs
  common/src/lib.rs
  common/src/utils.rs
  core/extensions/src/special_cells/mod.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/operation_test.rs
Labels: pr_refactor

#71 refactor: change handle transfer from normal address
  Cargo.lock
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/transfer_completion_test.rs
  core/rpc/src/types.rs
Labels: pr_refactor

#74 fix(rpc): get tx hash by script from indexer
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/query_test.rs
Labels: pr_fix

#67 feat(rpc): build asset collection transaction
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/types.rs
Labels: pr_feat

#77 fix: get cell from the previous tx output cell
  Cargo.lock
  Cargo.toml
  Makefile
  common/Cargo.toml
  core/extensions/Cargo.toml
  core/extensions/src/script_hash/mod.rs
  core/rpc/Cargo.toml
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/storage/Cargo.toml
Labels: pr_fix

#79 refactor(service): add ckb indexer rpc impl
  core/service/src/lib.rs
Labels: skip_changelog

#84 fix(rpc): insert output before drain
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/transfer.rs
Labels: skip_changelog

#85 feat(rpc): set default order of query_generic_transaction as desc
  core/rpc/README.md
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
Labels: pr_feat

#86 refactor: parse acp address from lock script
  common/src/address.rs
  core/extensions/src/tests/memory_store.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/tests/memory_db.rs
  devtools/config/testnet_config.toml
Labels: pr_refactor

#89 docs: add TOC
  core/rpc/README.md
Labels: pr_docs

#92 feat(service): relay ckb rpc request through mercury
  Cargo.lock
  Cargo.toml
  core/rpc/src/ckb_client.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/service/src/middleware.rs
Labels: pr_feat
