Repository nervosnetwork/mercury, pull requests merged in 2021-06, with the labels that each got.

#36 chore(ci): add PR kind labeler action
  .github/release-drafter.yml
  .github/workflows/pr_lint.yml
Labels: pr_chore, skip_changelog

#37 docs: update readme
  README.md
Labels: skip_changelog

#29 feat: update get_balance rpc
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
  src/extensions/ckb_balance/mod.rs
  src/extensions/ckb_balance/types.rs
  src/extensions/lock_time/mod.rs
  src/extensions/lock_time/types.rs
  src/extensions/tests/extension_test.rs
  src/extensions/tests/extension_test/ckb_balance_test.rs
  src/rpc/rpc_impl/query.rs
  src/rpc/tests/mod.rs
  src/rpc/tests/query_test.rs
  src/rpc/tests/transfer_completion.rs
Labels: pr_feat

#38 fix: calc cellbase capacity in ckb balance extension
  devtools/config/testnet_config.toml
  src/extensions/ckb_balance/mod.rs
  src/rpc/rpc_impl/query.rs
Labels: pr_fix

#39 docs: change config file path in README
  README.md
  devtools/config/testnet_config.toml
  src/rpc/rpc_impl/query.rs
Labels: pr_docs, skip_changelog

#42 feat(rpc): add ckb rpc client that support batch request
  Cargo.lock
  Cargo.toml
  clippy.toml
  src/cli.rs
  src/error.rs
  src/rpc/ckb_client.rs
  src/rpc/mod.rs
  src/rpc/rpc_impl.rs
  src/rpc/rpc_impl/query.rs
  src/rpc/rpc_impl/transfer.rs
  src/rpc/tests/mod.rs
  src/rpc/tests/query_test.rs
  src/service.rs
Labels: pr_feat

#45 refactor: get balance rpc interface and locktime extension
  core/extensions/src/ckb_balance/mod.rs
  core/extensions/src/ckb_balance/types.rs
  core/extensions/src/lib.rs
  core/extensions/src/lock_time/mod.rs
  core/extensions/src/lock_time/types.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/query_test.rs
  core/rpc/src/types.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_refactor

#46 fix: use filter instead of skip while in iterator
  core/extensions/src/lock_time/mod.rs
Labels: pr_fix

#47 fix: get others miner cellbase account iterator
  core/extensions/src/lock_time/mod.rs
Labels: pr_fix

#44 feat(rpc): add get transaction history interface
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/tests/query_test.rs
Labels: pr_feat

#50 refactor: downgrade tokio version to 0.2
  Cargo.lock
  Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/src/ckb_client.rs
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  src/main.rs
  tests/Cargo.toml
  tests/src/lib.rs
  tests/src/main.rs
Labels: pr_refactor

#49 feat: compatible address with acp
  Cargo.lock
  common/Cargo.toml
  common/src/address.rs
  common/src/lib.rs
  common/src/utils.rs
  core/extensions/Cargo.toml
  core/extensions/src/ckb_balance/mod.rs
  core/extensions/src/lib.rs
  core/extensions/src/lock_time/mod.rs
  core/extensions/src/special_cells/mod.rs
  core/extensions/src/tests/mod.rs
  core/extensions/src/udt_balance/mod.rs
  core/rpc/Cargo.toml
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/tests/mod.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
Labels: pr_feat

#52 ci(release): add auto compile and upload binaries
  .github/workflows/code_lint.yml
  .github/workflows/pr_lint.yml
  .github/workflows/release.yml
Labels: skip_changelog

#51 feat(rpc): add query charge block interface
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/types.rs
  core/service/src/lib.rs
Labels: pr_feat
