Repository nervosnetwork/mercury, pull requests merged in 2021-09, with the labels that each got.

#142 refactor(rpc): change asset status
  Cargo.lock
  Cargo.toml
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/types.rs
  core/service/Cargo.toml
Labels: pr_refactor

#143 refactor: change the cheque key address in record
  Cargo.lock
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
Labels: pr_refactor

#145 chore: bump tokio version to 1.11
  Cargo.lock
  Cargo.toml
  core/rpc/Cargo.toml
  core/service/Cargo.toml
  core/storage/Cargo.toml
  core/synchronization/Cargo.toml
Labels: pr_chore

#147 fix: get ckb locked balance and build record
  core/rpc/README.md
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/types.rs
Labels: pr_fix

#149 chore: upgrade jsonrpsee version
  Cargo.lock
  core/rpc/Cargo.toml
  core/service/Cargo.toml
Labels: pr_chore

#151 feat(sync): do synchronization in parallel
  Cargo.lock
  Cargo.toml
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/rpc/src/rpc_impl/utils.rs
  core/service/Cargo.toml
  core/service/src/lib.rs
  core/storage/Cargo.toml
  core/storage/src/kvdb/mod.rs
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/insert.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/table.rs
  core/synchronization/Cargo.toml
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
  core/synchronization/src/table.rs
  db/protocol/src/lib.rs
  db/rocksdb/Cargo.toml
  db/rocksdb/src/lib.rs
  db/xsql/src/lib.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
  devtools/create_table/create_table.sql
  src/main.rs
Labels: pr_feat

#155 feat(rpc): check is in tx pool cache when pool cell
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/utils.rs
  core/synchronization/src/lib.rs
Labels: pr_feat

#157 fix(sync): fetch all exist script hash
  Cargo.lock
  core/service/src/lib.rs
  core/synchronization/Cargo.toml
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
  core/synchronization/src/table.rs
Labels: pr_fix

#158 refactor(rpc): multiple requests by a same connection
  core/rpc/src/ckb_client.rs
Labels: pr_refactor

#159 refactor(storage): change append block process
  Cargo.lock
  core/cli/src/lib.rs
  core/storage/Cargo.toml
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/insert.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/sql.rs
  core/storage/src/relational/table.rs
Labels: pr_refactor

#160 chore: upgrade rust toolchain to 1.55
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/types.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/insert.rs
  core/storage/src/relational/table.rs
  rust-toolchain
Labels: pr_chore

#165 refactor(storage): change the return type of standalone sql
  Cargo.lock
  Cargo.toml
  Makefile
  core/rpc/src/tests/mod.rs
  core/storage/Cargo.toml
  core/storage/a.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/sql.rs
  core/storage/src/relational/table.rs
  core/storage/src/relational/tests/get_block_test.rs
  core/storage/src/relational/tests/get_cell_test.rs
  core/storage/src/relational/tests/get_tx_test.rs
  core/storage/src/relational/tests/mod.rs
  core/storage/src/relational/tests/other_test.rs
  core/storage/src/relational/tests/single_sql_test.rs
  core/synchronization/src/sql.rs
  core/synchronization/src/table.rs
  db/xsql-test/Cargo.toml
  db/xsql-test/src/lib.rs
  db/xsql-test/src/sql.rs
  devtools/create_table/create_sqlite_table.sql
  devtools/test_data/blocks/0.json
  devtools/test_data/blocks/1.json
  devtools/test_data/blocks/2.json
  devtools/test_data/blocks/3.json
  devtools/test_data/blocks/4.json
  devtools/test_data/blocks/5.json
  devtools/test_data/blocks/6.json
  devtools/test_data/blocks/7.json
  devtools/test_data/blocks/8.json
  devtools/test_data/blocks/9.json
Labels: pr_refactor

#166 refactor(storage): remove uncle relationship table
  Makefile
  core/storage/Cargo.toml
  core/storage/src/kvdb/mod.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/insert.rs
  core/storage/src/relational/table.rs
  core/synchronization/src/lib.rs
  db/rocksdb/Cargo.toml
  db/rocksdb/src/lib.rs
  db/xsql-test/src/lib.rs
  db/xsql-test/src/sql.rs
  devtools/create_table/create_sqlite_table.sql
  devtools/create_table/create_table.sql
Labels: pr_refactor

#164 feat(rpc): implement indexer rpc api get_tip
  core/rpc/src/indexer_types.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
Labels: pr_feat

#169 feat(storage): add get cell from cell table interface
  Cargo.lock
  Cargo.toml
  core/inspection/Cargo.toml
  core/inspection/src/lib.rs
  core/rpc/src/tests/rpc_test.rs
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/tests/get_cell_test.rs
Labels: pr_feat

#171 fix(storage): fix some bugs in storage and rpc
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/rpc_test.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/sql.rs
  core/synchronization/src/lib.rs
  db/xsql/src/page.rs
  devtools/test_data/blocks/100.json
Labels: pr_fix

#172 refactor(sync): change insert into mercury live cell process
  core/storage/src/relational/tests/mod.rs
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
Labels: pr_refactor

#173 feat(sql): add create index sql
  core/synchronization/src/lib.rs
  devtools/create_table/create_table.sql
Labels: pr_feat

#174 fix(rpc): fix some utils bug
  core/rpc/src/rpc_impl/utils.rs
  core/storage/src/relational/fetch.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_fix

#175 refactor(sync): free db transaction manually
  Cargo.lock
  core/synchronization/src/lib.rs
  devtools/config/mainnet_config.toml
Labels: pr_refactor

#176 refactor(rpc): remove trimmed 0x of json item
  Cargo.lock
  core/rpc/Cargo.toml
  core/rpc/src/types.rs
  core/service/Cargo.toml
Labels: pr_refactor

#177 refactor(rpc): swap init builtin scripts code hash
  core/rpc/src/rpc_impl.rs
Labels: pr_refactor

#179 chore(docker): mercury v0.2.0 docker-compose boot support
  .dockerignore
  .gitignore
  Dockerfile
  devtools/config/docker_compose_config.toml
  devtools/my-postgres.conf
  docker-compose.yml
Labels: pr_chore

#180 fix(rpc): debug get_balance
  common/src/utils.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/mod.rs
  core/storage/src/relational/fetch.rs
Labels: pr_fix

#181 feat(cli): add indexer mode option
  Cargo.lock
  core/cli/Cargo.toml
  core/cli/src/config.rs
  core/cli/src/lib.rs
  devtools/config/docker_compose_config.toml
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_feat

#183 feat(rpc): remove historical get_balance
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/tests/get_cell_test.rs
Labels: pr_feat

#184 fix(storage): query transactions by script hashes
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/types.rs
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
Labels: pr_fix

#185 fix(rpc): fix build_detailed_cell
  core/rpc/src/types.rs
  core/storage/src/relational/fetch.rs
Labels: pr_fix

#187 refactor(sync): extend cell table and deprecate consume info table
  common/src/lib.rs
  core/cli/src/lib.rs
  core/rpc/src/ckb_client.rs
  core/rpc/src/error.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl/query.rs
  core/service/src/lib.rs
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/insert.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/remove.rs
  core/storage/src/relational/sql.rs
  core/storage/src/relational/table.rs
  core/storage/src/relational/tests/get_cell_test.rs
  core/storage/src/relational/tests/mod.rs
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
  core/synchronization/src/table.rs
  db/xsql-test/src/sql.rs
  devtools/create_table/create_sqlite_table.sql
  devtools/create_table/create_table.sql
Labels: pr_refactor

#188 feat(rpc): add get ckb uri interface
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
Labels: pr_feat

#190 fix(rpc): debug dao conversion
  common/src/utils.rs
  core/rpc/src/rpc_impl/utils.rs
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
Labels: pr_fix

#189 fix(docker): Ignore docker volume data at build
  .dockerignore
Labels: pr_fix

#192 feat(storage): add query historical live cell interface
  core/rpc/src/rpc_impl/utils.rs
  core/storage/src/lib.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
Labels: pr_feat

#193 fix(rpc): fix history get_balance
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/types.rs
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
Labels: pr_fix

#196 fix(rpc): debug get_transaction_info
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#170 feat(rpc): add build adjust account transaction interface
  Cargo.lock
  common/src/hash.rs
  core/rpc/src/ckb_client.rs
  core/rpc/src/lib.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/adjust_account.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/operation.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/transfer.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/tests/mod.rs
  core/rpc/src/tests/sqlite/mod.rs
  core/rpc/src/types.rs
Labels: pr_feat

#198 fix(rpc): enable negative fee
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/types.rs
Labels: pr_fix

#199 fix(rpc): fix build_deposit_transaction
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/consts.rs
Labels: pr_fix

#201 refactor(rpc): change update adjust account change cell
  Cargo.lock
  core/rpc/src/rpc_impl/adjust_account.rs
  core/rpc/src/rpc_impl/build_tx.rs
Labels: pr_refactor

#202 fix(docker): docker-compose path error
  docker-compose.yml
Labels: pr_fix

#203 fix(rpc): fix build_withdraw
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#205 fix(rpc): debug build_transfer_transaction
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
  core/rpc/src/types.rs
  devtools/create_table/create_table.sql
Labels: pr_fix

#209 fix(rpc): change output acp cell data
  core/rpc/src/rpc_impl/adjust_account.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#211 fix(rpc): skip lock_hashes is empty
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#213 fix(rpc): add indexer for consumend_tx_hash in cell table
  core/rpc/src/rpc_impl/build_tx.rs
  devtools/create_table/create_table.sql
Labels: pr_fix

#212 fix(rpc): split acp cells and calculate actual fee
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/adjust_account.rs
Labels: pr_fix

#215 fix(rpc): add change cell of build account output
  core/rpc/src/rpc_impl/adjust_account.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#216 fix(rpc): fix claimable
  common/src/lib.rs
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#217 fix(rpc): fix get_spend_transaction
  core/rpc/src/rpc_impl/query.rs
Labels: pr_fix

#218 fix(storage): fetch cell between block range
  Cargo.lock
  core/rpc/src/lib.rs
  core/service/src/lib.rs
  core/storage/src/relational/fetch.rs
Labels: pr_fix

#219 fix(rpc): update change cell in transaction view
  core/rpc/src/rpc_impl/adjust_account.rs
Labels: pr_fix

#220 fix(rpc): debug build_smart_transaction
  common/src/address.rs
  core/rpc/README.md
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#221 fix: fetch transaction with pagination request
  core/storage/src/relational/fetch.rs
  core/storage/src/relational/mod.rs
Labels: pr_fix

#223 fix(rpc): debug build_adjust_account_transaction
  core/rpc/README.md
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl.rs
  core/rpc/src/rpc_impl/adjust_account.rs
  core/rpc/src/rpc_impl/utils.rs
Labels: pr_fix

#222 fix(storage): next cursor of pagination response
  common/src/lib.rs
  core/storage/src/relational/fetch.rs
  db/xsql/src/page.rs
Labels: pr_fix

#224 refactor(common): change default order to ascend
  common/src/lib.rs
Labels: pr_refactor

#225 docs: update README
  README.md
  db/xsql/src/page.rs
Labels: pr_docs

#226 fix(rpc): debug build_adjust_account_transaction
  core/rpc/src/rpc_impl/adjust_account.rs
Labels: pr_fix

#228 refactor: change next cursor of pagination
  apm/tracing/Cargo.toml
  core/rpc/Cargo.toml
  core/storage/Cargo.toml
  core/storage/src/relational/fetch.rs
  db/xsql/Cargo.toml
Labels: pr_refactor

#231 fix(storage): recover Byte32 from database
  core/storage/src/relational/fetch.rs
Labels: pr_fix

#232 fix(rpc): fix dao withdraw
  core/rpc/src/rpc_impl/build_tx.rs
  devtools/config/testnet_config.toml
Labels: pr_fix

#236 fix(common): fix pubkey too long cause panic
  common/src/address.rs
Labels: pr_fix

#238 feat(rpc): split change cell to ckb change and udt change
  core/rpc/src/rpc_impl/build_tx.rs
Labels: pr_feat

#239 refactor: change release action
  .github/workflows/release.yml
Labels: pr_refactor

#241 chore: update readme
  README.md
Labels: pr_chore

#242 refactor(rpc): remove unwrap instead of return error
  Cargo.lock
  Cargo.toml
  apm/tracing/Cargo.toml
  core/cli/Cargo.toml
  core/inspection/Cargo.toml
  core/rpc/Cargo.toml
  core/rpc/src/error.rs
  core/rpc/src/rpc_impl/adjust_account.rs
  core/rpc/src/rpc_impl/build_tx.rs
  core/rpc/src/rpc_impl/query.rs
  core/rpc/src/rpc_impl/utils.rs
  core/service/Cargo.toml
  core/storage/Cargo.toml
  core/synchronization/Cargo.toml
Labels: pr_refactor

#243 feat(cli): add some cmd args for mercury
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  core/cli/src/lib.rs
  core/storage/src/relational/mod.rs
Labels: pr_feat

#244 fix(storage): update consumed info at the end of append
  core/storage/src/relational/insert.rs
  core/storage/src/relational/mod.rs
  core/storage/src/relational/table.rs
Labels: pr_fix

#245 fix(sql): fix index error in live cell table
  devtools/create_table/create_table.sql
Labels: pr_fix

#247 refactor: remove rocksdb and refactor sync process
  Cargo.lock
  README.md
  core/cli/src/config.rs
  core/cli/src/lib.rs
  core/service/src/lib.rs
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
  core/synchronization/src/table.rs
  devtools/config/docker_compose_config.toml
  devtools/config/mainnet_config.toml
  devtools/config/testnet_config.toml
  devtools/create_table/create_table.sql
Labels: pr_refactor

#249 feat(sync): paginate update and insert into by block number
  Cargo.lock
  core/synchronization/Cargo.toml
  core/synchronization/src/lib.rs
  core/synchronization/src/sql.rs
Labels: pr_feat

#250 fix(storage): rollback block method
  core/storage/src/relational/remove.rs
Labels: pr_fix
